apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-meet.jicofo.fullname" . }}
  labels:
    {{- include "jitsi-meet.jicofo.labels" . | nindent 4 }}
data:
  JICOFO_ENABLE_REST: "1"
  JVB_BREWERY_MUC: {{ .Values.jvb.breweryMuc | quote}}
  XMPP_SERVER: {{ include "jitsi-meet.xmpp.server" . | quote }}

  {{- if .Values.jibri.enabled }}
  JIBRI_BREWERY_MUC: {{ .Values.jibri.breweryMuc | quote }}
  JIBRI_PENDING_TIMEOUT: {{ .Values.jibri.timeout | quote }}
  {{- end }}

  {{- if .Values.jigasi.enabled }}
  JIGASI_BREWERY_MUC: {{ .Values.jigasi.breweryMuc | quote}}
  JIGASI_SIP_URI: "available"
  {{- end }}

  {{- if .Values.transcriber.enabled }}
  ENABLE_TRANSCRIPTIONS: "1"
  {{- end }}

  {{- if .Values.octo.enabled }}
  ENABLE_OCTO: "1"
  OCTO_BRIDGE_SELECTION_STRATEGY: "RegionBasedBridgeSelectionStrategy"
  {{- end }}

  {{- range $key, $value := .Values.jicofo.extraEnvs }}
  {{-   if not (kindIs "invalid" $value) }}
  {{      $key }}: {{ tpl $value $ | quote }}
  {{-   end }}
  {{- end }}
