apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsi-meet.jicofo.fullname" . }}
  labels:
    {{- include "jitsi-meet.jicofo.labels" . | nindent 4 }}
  {{- with .Values.jicofo.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "jitsi-meet.jicofo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jitsi-meet.jicofo.selectorLabels" . | nindent 8 }}
        {{- with (mergeOverwrite .Values.global.podLabels .Values.jicofo.podLabels) }}
        {{- toYaml . | nindent 8  }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/jicofo/configmap.yaml") . | sha256sum | quote }}
        checksum/secret: {{ include (print $.Template.BasePath "/jicofo/secret.yaml") . | sha256sum | quote }}
        {{- with (mergeOverwrite .Values.global.podAnnotations .Values.jicofo.podAnnotations) }}
        {{- toYaml . | nindent 8  }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jitsi-meet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.jicofo.podSecurityContext | nindent 8 }}
      volumes:
      - name: config
        emptyDir: {}
      - name: custom-continit
        configMap:
          defaultMode: 493
          name: {{ include "jitsi-meet.jicofo.fullname" . }}-continit
      - name: custom-defaults
        configMap:
          name: {{ include "jitsi-meet.jicofo.fullname" . }}-defaults
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.jicofo.image.repository }}:{{ .Values.jicofo.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ pluck "pullPolicy" .Values.jicofo.image .Values.image | first }}
          securityContext:
            {{- toYaml .Values.jicofo.securityContext | nindent 12 }}
          envFrom:
          - secretRef:
              name: {{ include "jitsi-meet.jicofo.secretName" . }}
          - configMapRef:
              name: {{ include "jitsi-meet.common" . }}
          - configMapRef:
              name: {{ include "jitsi-meet.jicofo.fullname" . }}
          {{- if .Values.global.releaseSecretsOverride.enabled }}
          {{-   range .Values.global.releaseSecretsOverride.extraEnvFrom }}
          - {{    tpl (toYaml . ) $ | indent 12 | trim }}
          {{-   end }}
          {{- end }}
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          {{- with .Values.jicofo.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.jicofo.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.jicofo.resources | nindent 12 }}
          volumeMounts:
          # to support readOnlyRootFilesystem
          - name: config
            mountPath: /config
          {{- if .Values.jicofo.custom.contInit._10_config }}
          - name: custom-continits
            mountPath: /etc/cont-init.d/10-config
            subPath: 10-config
          {{- end }}
          {{- if .Values.jicofo.custom.defaults._jicofo_conf }}
          - name: custom-defaults
            mountPath: /defaults/jicofo.conf
            subPath: jicofo.conf
          {{- end }}
          {{- if .Values.jicofo.custom.defaults._logging_properties }}
          - name: custom-defaults
            mountPath: /defaults/logging.properties
            subPath: logging.properties
          {{- end }}

        {{- if .Values.jicofo.metrics.enabled }}
        - name: metrics
          image: "{{ .Values.jicofo.metrics.image.repository }}:{{ .Values.jicofo.metrics.image.tag }}"
          imagePullPolicy: {{ pluck "pullPolicy" .Values.jicofo.metrics.image .Values.image | first }}
          ports:
          - name: metrics
            containerPort: 9996
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 9996
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.jicofo.metrics.resources | nindent 12 }}
        {{- end }}

      {{- with .Values.jicofo.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jicofo.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jicofo.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
