{{- if and
    .Values.jigasi.enabled
    (not .Values.jigasi.useExternalJigasi)
}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsi-meet.jigasi.fullname" . }}
  labels:
    {{- include "jitsi-meet.jigasi.labels" . | nindent 4 }}
  {{- with .Values.jigasi.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "jitsi-meet.jigasi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jitsi-meet.jigasi.selectorLabels" . | nindent 8 }}
        {{- with (mergeOverwrite .Values.global.podLabels .Values.jigasi.podLabels) }}
        {{- toYaml . | nindent 8  }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/jigasi/configmap.yaml") . | sha256sum | quote }}
        checksum/secret: {{ include (print $.Template.BasePath "/jigasi/secret.yaml") . | sha256sum | quote }}
        {{- with (mergeOverwrite .Values.global.podAnnotations .Values.jigasi.podAnnotations) }}
        {{- toYaml . | nindent 8  }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jigasi.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jitsi-meet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.jigasi.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-prosody
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for Prosody on port 5280";
              while ! nc -z -w 1 {{ include "jitsi-meet.xmpp.server" . }} 5280; do
                sleep 1;
              done;
              echo ">> Prosody is available"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.jigasi.image.repository }}:{{ .Values.jigasi.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ pluck "pullPolicy" .Values.jigasi.image .Values.image | first }}
          securityContext:
            {{- toYaml .Values.jigasi.securityContext | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ include "jitsi-meet.jigasi.secretName" . }}
            - configMapRef:
                name: {{ include "jitsi-meet.common" . }}
            - configMapRef:
                name: {{ include "jitsi-meet.jigasi.fullname" . }}
            {{- range .Values.jigasi.extraEnvFrom }}
            - {{  tpl (toYaml . ) $ | indent 14 | trim }}
            {{- end }}
            {{- if .Values.global.releaseSecretsOverride.enabled }}
            {{-   range .Values.global.releaseSecretsOverride.extraEnvFrom }}
            - {{    tpl (toYaml . ) $ | indent 14 | trim }}
            {{-   end }}
            {{- end }}
          {{- with .Values.jigasi.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.jigasi.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.jigasi.resources | nindent 12 }}

      {{- with .Values.jigasi.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jigasi.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jigasi.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
