{{- if and .Values.coturn.enabled .Values.coturn.turns.enabled .Values.coturn.turns.certificate.acmeProxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-meet.coturn.fullname" . }}-acme-proxy
  labels:
    {{- include "jitsi-meet.coturn.labels" . | nindent 4 }}
data:
  nginx.conf: |
    events {
      worker_connections 16;
    }
    http {
      server {
        listen 80;
        server_name _;

        location /.well-known/acme-challenge/ {
          proxy_pass http://{{ required "coturn.turns.certificate.acmeProxy.target is required" .Values.coturn.turns.certificate.acmeProxy.target }}:{{ .Values.coturn.turns.certificate.acmeProxy.targetPort }};
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
          return 404;
        }
      }
    }
{{- end }}
