{{- if .Values.coturn.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsi-meet.coturn.fullname" . }}
  labels:
    {{- include "jitsi-meet.coturn.labels" . | nindent 4 }}
  {{- with .Values.coturn.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.coturn.replicaCount }}
  selector:
    matchLabels:
      {{- include "jitsi-meet.coturn.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jitsi-meet.coturn.selectorLabels" . | nindent 8 }}
        {{- with (mergeOverwrite .Values.global.podLabels .Values.coturn.podLabels) }}
        {{- toYaml . | nindent 8  }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/coturn/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/coturn/secret.yaml") . | sha256sum }}
        {{- with (mergeOverwrite .Values.global.podAnnotations .Values.coturn.podAnnotations) }}
        {{- toYaml . | nindent 8  }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jitsi-meet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.coturn.podSecurityContext | nindent 8 }}
      volumes:
        - name: config-dir
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "jitsi-meet.coturn.fullname" . }}-config
      initContainers:
      - name: init-coturn
        image: busybox:1.36
        command:
          - sh
          - -c
          - |
            chmod 755 /config-dir && \
            cp /turnserver.conf /config-dir/ && \
            echo >>/config-dir/turnserver.conf && \
            echo "static-auth-secret=$TURN_CREDENTIALS" >>/config-dir/turnserver.conf
        envFrom:
        - secretRef:
            name: {{ include "jitsi-meet.coturn.secretName" . }}
        volumeMounts:
        - name: config-dir
          mountPath: /config-dir
        - name: config
          mountPath: /turnserver.conf
          subPath: turnserver.conf
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.coturn.image.repository }}:{{ .Values.coturn.image.tag }}"
          imagePullPolicy: {{ pluck "pullPolicy" .Values.coturn.image .Values.image | first }}
          securityContext:
            {{- toYaml .Values.coturn.securityContext | nindent 12 }}
          envFrom:
          - secretRef:
              name: {{ include "jitsi-meet.coturn.secretName" . }}
          - configMapRef:
              name: {{ include "jitsi-meet.common" . }}
          - configMapRef:
              name: {{ include "jitsi-meet.coturn.fullname" . }}
          - configMapRef:
              name: {{ include "jitsi-meet.coturn.fullname" . }}-config
          {{- if .Values.global.releaseSecretsOverride.enabled }}
          {{- range .Values.global.releaseSecretsOverride.extraEnvFrom }}
          - {{ tpl (toYaml . ) $ | indent 12 | trim }}
          {{- end }}
          {{- end }}
          ports:
          - name: tcp-turn
            protocol: TCP
            containerPort: {{ index .Values.coturn.service.ports "turn" }}
          - name: udp-turn
            protocol: UDP
            containerPort: {{ index .Values.coturn.service.ports "turn" }}
          {{- with .Values.coturn.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.coturn.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.coturn.resources | nindent 12 }}
          volumeMounts:
          - name: config-dir
            mountPath: /etc/coturn
            readOnly: true

      {{- with .Values.coturn.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.coturn.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.coturn.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
