{{- if .Values.coturn.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsi-meet.coturn.fullname" . }}
  labels:
    {{- include "jitsi-meet.coturn.labels" . | nindent 4 }}
  {{- with .Values.coturn.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.coturn.replicaCount }}
  selector:
    matchLabels:
      {{- include "jitsi-meet.coturn.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jitsi-meet.coturn.selectorLabels" . | nindent 8 }}
        {{- range $label, $value := mergeOverwrite .Values.global.podLabels .Values.coturn.podLabels }}
        {{    $label }}: {{ $value }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/coturn/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/coturn/secret.yaml") . | sha256sum }}
        {{- range $annotation, $value := mergeOverwrite .Values.global.podAnnotations .Values.coturn.podAnnotations }}
        {{    $annotation }}: {{ $value | quote }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jitsi-meet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.coturn.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.coturn.securityContext | nindent 12 }}
          image: "{{ .Values.coturn.image.repository }}:{{ default .Chart.AppVersion .Values.coturn.image.tag }}"
          imagePullPolicy: {{ pluck "pullPolicy" .Values.coturn.image .Values.image | first }}
          envFrom:
          - secretRef:
              name: {{ include "jitsi-meet.coturn.secretName" . }}
          - configMapRef:
              name: {{ include "jitsi-meet.common" . }}
          - configMapRef:
              name: {{ include "jitsi-meet.coturn.fullname" . }}
          {{- if .Values.global.releaseSecretsOverride.enabled }}
          {{- range .Values.global.releaseSecretsOverride.extraEnvFrom }}
          - {{ tpl (toYaml . ) $ | indent 12 | trim }}
          {{- end }}
          {{- end }}
          {{- with .Values.coturn.livenessProbe }}
          ports:
            - name: tcp-turns
              containerPort: {{ index .Values.coturn.service.ports "turns" }}
              protocol: TCP
            - name: tcp-stun
              containerPort: {{ index .Values.coturn.service.ports "stun" }}
              protocol: TCP
            - name: udp-stun
              containerPort: {{ index .Values.coturn.service.ports "stun" }}
              protocol: UDP
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.coturn.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.coturn.resources | nindent 12 }}

      {{- with .Values.coturn.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.coturn.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.coturn.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
