{{- if .Values.coturn.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.coturn.fullname" . }}
  labels:
    {{- include "jitsi-meet.coturn.labels" . | nindent 4 }}
  {{- with .Values.coturn.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.coturn.service.type }}
  {{- if eq .Values.coturn.service.type "LoadBalancer" }}
  allocateLoadBalancerNodePorts: {{ .Values.coturn.service.allocateLoadBalancerNodePorts }}
  {{- end }}
  {{- if and
         .Values.coturn.turns.enabled
         .Values.coturn.turns.certificate.acmeProxy.enabled
  }}
  publishNotReadyAddresses: true
  {{- end }}
  {{- with .Values.coturn.service.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  ports:
    - name: udp-turn
      protocol: UDP
      port: {{ .Values.coturn.service.ports.turn }}
    {{- if .Values.coturn.turns.enabled }}
    - name: tcp-turns
      protocol: TCP
      port: {{ .Values.coturn.service.ports.turns }}
    {{- end }}
    {{- if and
           .Values.coturn.turns.enabled
           .Values.coturn.turns.certificate.acmeProxy.enabled
    }}
    - name: http-acme
      protocol: TCP
      port: 80
    {{- end }}
  selector:
    {{- include "jitsi-meet.coturn.selectorLabels" . | nindent 4 }}
{{- end }}
