{{- if .Values.coturn.enabled }}
{{- $udpEnabled := .Values.coturn.transport.udp | default true -}}
{{- $tcpEnabled := .Values.coturn.transport.tcp | default false -}}
{{- if and (not $udpEnabled) (not $tcpEnabled) -}}
{{- $udpEnabled = true -}}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.coturn.fullname" . }}
  labels:
    {{- include "jitsi-meet.coturn.labels" . | nindent 4 }}
  {{- with .Values.coturn.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.coturn.service.type }}
  {{- with .Values.coturn.service.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  ports:
    {{- if $udpEnabled }}
    - name: udp-turn
      protocol: UDP
      port: {{ index .Values.coturn.service.ports "turn" }}
    {{- end }}
    {{- if $tcpEnabled }}
    - name: tcp-turn
      protocol: TCP
      port: {{ index .Values.coturn.service.ports "turn" }}
    {{- end }}
  selector:
    {{- include "jitsi-meet.coturn.selectorLabels" . | nindent 4 }}
{{- end }}
