{{- if .Values.coturn.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.coturn.fullname" . }}
  labels:
    {{- include "jitsi-meet.coturn.labels" . | nindent 4 }}
  {{- with .Values.coturn.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.coturn.service.type }}
  {{- if and .Values.coturn.turns.enabled .Values.coturn.turns.certificate.acmeProxy.enabled }}
  publishNotReadyAddresses: true
  {{- end }}
  {{- with .Values.coturn.service.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  ports:
    {{- if not .Values.coturn.turns.enabled }}
    - name: udp-turn
      protocol: UDP
      port: {{ index .Values.coturn.service.ports "turn" }}
    {{- end }}
    {{- if .Values.coturn.turns.enabled }}
    - name: tcp-turns
      protocol: TCP
      port: {{ .Values.coturn.turns.port }}
    {{- end }}
    {{- if .Values.coturn.turns.enabled }}
    {{- $min := int .Values.coturn.turns.relayPortRange.min }}
    {{- $max := int .Values.coturn.turns.relayPortRange.max }}
    {{- if gt $min $max }}
    {{- fail "coturn.turns.relayPortRange.min must be <= coturn.turns.relayPortRange.max" }}
    {{- end }}
    {{- $maxPlus := add $max 1 | int }}
    {{- range $port := untilStep $min $maxPlus 1 }}
    - name: relay-udp-{{ $port }}
      protocol: UDP
      port: {{ $port }}
      targetPort: {{ $port }}
    {{- end }}
    {{- end }}
    {{- if and .Values.coturn.turns.enabled .Values.coturn.turns.certificate.acmeProxy.enabled }}
    - name: http-acme
      protocol: TCP
      port: 80
    {{- end }}
  selector:
    {{- include "jitsi-meet.coturn.selectorLabels" . | nindent 4 }}
{{- end }}
