apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-meet.web.fullname" . }}-init
  labels:
    {{- include "jitsi-meet.web.labels" . | nindent 4 }}
data:
  10-config: |
  {{- if .Values.web.custom.contInit._10_config }}
    {{- .Values.web.custom.contInit._10_config | nindent 4 }}
  {{- else }}
  # Using web /etc/cont-init.d/10-config from container image
  {{ end }}
