{{- if .Values.web.custom.contInit._10_config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-meet.web.fullname" . }}-continit
  labels:
    {{- include "jitsi-meet.web.labels" . | nindent 4 }}
data:
  10-config: |
    {{- .Values.web.custom.contInit._10_config | nindent 4 }}
{{- end }}
