apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.web.fullname" . }}
  labels:
    {{- include "jitsi-meet.web.labels" . | nindent 4 }}
  {{- with .Values.web.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.web.service.port }}
      {{- with .Values.web.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  {{- with .Values.web.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "jitsi-meet.web.selectorLabels" . | nindent 4 }}
