{{- if and
    .Values.transcriber.enabled
    (not .Values.transcriber.useExternalTranscriber)
}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsi-meet.transcriber.fullname" . }}
  labels:
    {{- include "jitsi-meet.transcriber.labels" . | nindent 4 }}
  {{- with .Values.transcriber.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "jitsi-meet.transcriber.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jitsi-meet.transcriber.selectorLabels" . | nindent 8 }}
        {{- range $label, $value := mergeOverwrite .Values.global.podLabels .Values.transcriber.podLabels }}
        {{    $label }}: {{ $value }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/transcriber/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/transcriber/secret.yaml") . | sha256sum }}
        {{- range $annotation, $value := mergeOverwrite .Values.global.podAnnotations .Values.transcriber.podAnnotations }}
        {{    $annotation }}: {{ $value | quote }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jitsi-meet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.transcriber.podSecurityContext | nindent 8 }}
      volumes:
      - name: transcriber-data
        {{- if .Values.transcriber.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.transcriber.persistence.existingClaim | default (include "jitsi-meet.transcriber.fullname" .) }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      initContainers:
      - name: init-prosody
        image: busybox:1.36
        command:
          - sh
          - -c
          - |
            echo "Waiting for Prosody on port 5280";
            while ! nc -z -w 1 {{ include "jitsi-meet.xmpp.server" . }} 5280; do
              sleep 1;
            done;
            echo ">> Prosody is available"
      containers:
        - name: {{ .Chart.Name }}-transcriber
          image: "{{ .Values.transcriber.image.repository }}:{{ default .Chart.AppVersion .Values.transcriber.image.tag }}"
          imagePullPolicy: {{ pluck "pullPolicy" .Values.transcriber.image .Values.image | first }}
          securityContext:
            {{- toYaml .Values.transcriber.securityContext | nindent 12 }}
          envFrom:
          - secretRef:
              name: {{ include "jitsi-meet.transcriber.secret" . }}
          - configMapRef:
              name: {{ include "jitsi-meet.common" . }}
          - configMapRef:
              name: {{ include "jitsi-meet.transcriber.fullname" . }}
          {{- if .Values.global.releaseSecretsOverride.enabled }}
          {{-   range .Values.global.releaseSecretsOverride.extraEnvFrom }}
          - {{    tpl (toYaml .) $ | indent 12 | trim }}
          {{-   end }}
          {{- end }}
          {{- with .Values.transcriber.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.transcriber.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.transcriber.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.transcriber.persistence.enabled }}
          - name: transcriber-data
            mountPath: /tmp/transcripts
          {{- end }}

      {{- with .Values.transcriber.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.transcriber.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.transcriber.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
