apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.prosody.fullname" . }}
  labels:
    {{- include "jitsi-meet.prosody.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prosody.service.type }}
  ports:
    - port: {{ index .Values.prosody.service.ports "bosh-insecure" }}
      protocol: TCP
      name: tcp-bosh-insecure
    - port: {{ index .Values.prosody.service.ports "bosh-secure" }}
      protocol: TCP
      name: tcp-bosh-secure
    - port: {{ index .Values.prosody.service.ports "xmpp-component" }}
      protocol: TCP
      name: tcp-xmpp-component
    - port: {{ index .Values.prosody.service.ports "xmpp-c2s" }}
      protocol: TCP
      name: tcp-xmpp-c2
      {{- if .Values.prosody.service.ports.xmppc2snodePort }}
      nodePort: {{ index .Values.prosody.service.ports "xmppc2snodePort" }}
      {{- end }}
    - port: {{ index .Values.prosody.service.ports "xmpp-s2s" }}
      protocol: TCP
      name: tcp-xmpp-s2
    {{- if .Values.prosody.metrics.enabled }}
    - port: 8889
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "jitsi-meet.prosody.selectorLabels" . | nindent 4 }}
