{{- if .Values.excalidraw.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.excalidraw.fullname" . }}
  labels:
    {{- include "jitsi-meet.excalidraw.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: metrics
      protocol: TCP
      port: 9090
  selector:
    {{- include "jitsi-meet.excalidraw.selectorLabels" . | nindent 4 }}
{{- end }}
